//
//  UIFont+Zeplin.swift
//
//  Generated by Zeplin on 6/15/16.
//  Copyright (c) 2016 Yalantis. All rights reserved.
//

import UIKit

extension UIFont {
    
    class func largeTitleFont() -> UIFont? {
        return UIFont(name: "Gotham Pro Black Regular", size: 20.0)
    }
    
    class func navigationTitleFont() -> UIFont? {
        return UIFont(name: "Gotham Pro Medium Regular", size: 24.0)
    }
    
    class func cellTitleFont() -> UIFont? {
        return UIFont(name: "GothamPro-Bold", size: 18.0)
    }
    
    class func menuTitleFont() -> UIFont? {
        return UIFont(name: "GothamPro", size: 15.0)
    }
    
    class func cellSubtitleFont() -> UIFont? {
        return UIFont(name: "Gotham Pro Medium Regular", size: 12.0)
    }
    
    class func regularTitleFont18() -> UIFont? {
        return UIFont(name: "GothamPro", size: 18.0)
    }
    
    class func regularTitleFont16() -> UIFont? {
        return UIFont(name: "GothamPro", size: 16.0)
    }
    
    class func regularTitleFont12() -> UIFont? {
        return UIFont(name: "GothamPro", size: 12.0)
    }
    
    class func fontAvenirMedium(ofSize size: CGFloat) -> UIFont {
        return UIFont(name: "Avenir-Book", size: size) ?? UIFont.systemFont(ofSize: size)
    }
    
    class func fontAvenirLight(ofSize size: CGFloat) -> UIFont {
        return UIFont(name: "Avenir-Light", size: size) ?? UIFont.systemFont(ofSize: size)
    }
}
